version: '3'

services:
    web:
        image: nginx:1.14-alpine
        network_mode: "host"
        volumes:
            - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            - NGINX_PORT=1234
